#!/usr/bin/env python3
"""
Approval Workflow

Manages human-in-the-loop approval for sensitive actions.
Monitors Pending_Approval, Approved, and Rejected folders.
"""

import sys
import shutil
from pathlib import Path
from datetime import datetime
from typing import List, Tuple, Optional
import logging


class ApprovalWorkflow:
    """
    Manages approval workflow for sensitive actions.
    """
    
    def __init__(self, vault_path: str):
        """
        Initialize approval workflow.
        
        Args:
            vault_path: Path to the Obsidian vault root
        """
        self.vault_path = Path(vault_path)
        self.pending_approval = self.vault_path / 'Pending_Approval'
        self.approved = self.vault_path / 'Approved'
        self.rejected = self.vault_path / 'Rejected'
        self.done = self.vault_path / 'Done'
        self.logs = self.vault_path / 'Logs'
        
        # Ensure folders exist
        for folder in [self.pending_approval, self.approved, self.rejected, self.logs]:
            folder.mkdir(parents=True, exist_ok=True)
        
        # Set up logging
        self._setup_logging()
        
        self.logger.info('Approval Workflow initialized')
    
    def _setup_logging(self) -> None:
        """Set up logging."""
        self.logger = logging.getLogger('ApprovalWorkflow')
        self.logger.setLevel(logging.INFO)
        
        if not self.logger.handlers:
            handler = logging.StreamHandler()
            formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
            handler.setFormatter(formatter)
            self.logger.addHandler(handler)
    
    def get_pending_approvals(self) -> List[Path]:
        """Get all pending approval files."""
        return list(self.pending_approval.glob('*.md'))
    
    def get_approved_actions(self) -> List[Path]:
        """Get all approved action files."""
        return list(self.approved.glob('*.md'))
    
    def get_rejected_actions(self) -> List[Path]:
        """Get all rejected action files."""
        return list(self.rejected.glob('*.md'))
    
    def create_approval_request(
        self,
        action_type: str,
        title: str,
        details: dict,
        source_file: Optional[Path] = None
    ) -> Path:
        """
        Create an approval request file.
        
        Args:
            action_type: Type of action (payment, email_send, etc.)
            title: Title for the approval request
            details: Dictionary of action details
            source_file: Original action file path
            
        Returns:
            Path to created approval request file
        """
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'APPROVAL_{title}_{timestamp}.md'
        filepath = self.pending_approval / filename
        
        # Build details section
        details_text = '\n'.join([f'- **{k.replace("_", " ").title()}:** {v}' for k, v in details.items()])
        
        content = f'''---
type: approval_request
action_type: {action_type}
created: {datetime.now().isoformat()}
status: pending
source_file: {source_file.name if source_file else 'manual'}
---

# Approval Request: {title}

## Action Details

{details_text}

## Instructions

**To Approve:**
1. Review the action details above
2. Move this file to `/Approved` folder
3. System will execute the action automatically

**To Reject:**
1. Move this file to `/Rejected` folder
2. Add reason for rejection in the Notes section below

## Notes

Add your decision reason here:

---

## Audit Trail

| Timestamp | Action | Status |
|-----------|--------|--------|
| {datetime.now().isoformat()} | Approval request created | Pending |

---

*Generated by Personal AI Employee Hackathon-0 Approval Workflow v0.1 (Silver Tier)*
'''
        
        filepath.write_text(content, encoding='utf-8')
        self.logger.info(f'Approval request created: {filename}')
        
        return filepath
    
    def process_approved(self) -> List[Tuple[Path, str]]:
        """
        Process all approved actions.
        
        Returns:
            List of (file_path, action_type) tuples
        """
        processed = []
        
        for approved_file in self.get_approved_actions():
            try:
                content = approved_file.read_text(encoding='utf-8')
                
                # Extract action type from frontmatter
                action_type = self._extract_frontmatter_value(content, 'action_type')
                
                self.logger.info(f'Approved action ready: {approved_file.name} (type: {action_type})')
                processed.append((approved_file, action_type or 'unknown'))
                
            except Exception as e:
                self.logger.error(f'Error processing approved file {approved_file.name}: {e}')
        
        return processed
    
    def process_rejected(self) -> List[Path]:
        """
        Process all rejected actions (move to Done with REJECTED prefix).
        
        Returns:
            List of processed file paths
        """
        processed = []
        
        for rejected_file in self.get_rejected_actions():
            try:
                # Move to Done with REJECTED prefix
                dest = self.done / f'REJECTED_{rejected_file.name}'
                shutil.move(str(rejected_file), str(dest))
                
                self.logger.info(f'Rejected action archived: {dest.name}')
                processed.append(dest)
                
                # Log rejection
                self._log_action(dest.name, 'rejected', 'archived')
                
            except Exception as e:
                self.logger.error(f'Error processing rejected file {rejected_file.name}: {e}')
        
        return processed
    
    def move_to_approved(self, source_file: Path) -> Path:
        """
        Move a file from Pending_Approval to Approved.
        
        Args:
            source_file: Path to file in Pending_Approval
            
        Returns:
            Path to file in Approved folder
        """
        dest = self.approved / source_file.name
        shutil.move(str(source_file), str(dest))
        
        self.logger.info(f'File approved: {source_file.name} -> {dest.name}')
        self._log_action(source_file.name, 'approved', 'moved_to_approved')
        
        return dest
    
    def move_to_rejected(self, source_file: Path) -> Path:
        """
        Move a file from Pending_Approval to Rejected.
        
        Args:
            source_file: Path to file in Pending_Approval
            
        Returns:
            Path to file in Rejected folder
        """
        dest = self.rejected / source_file.name
        shutil.move(str(source_file), str(dest))
        
        self.logger.info(f'File rejected: {source_file.name} -> {dest.name}')
        self._log_action(source_file.name, 'rejected', 'moved_to_rejected')
        
        return dest
    
    def _extract_frontmatter_value(self, content: str, key: str) -> Optional[str]:
        """Extract a value from YAML frontmatter."""
        lines = content.split('\n')
        in_frontmatter = False
        
        for line in lines:
            if line.strip() == '---':
                if not in_frontmatter:
                    in_frontmatter = True
                    continue
                else:
                    break
            
            if in_frontmatter and line.startswith(f'{key}:'):
                value = line.split(':', 1)[1].strip().strip('"\'')
                return value
        
        return None
    
    def _log_action(self, filename: str, action_type: str, status: str) -> None:
        """Log an action to the audit log."""
        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'file': filename,
            'action_type': action_type,
            'status': status,
            'actor': 'approval_workflow'
        }
        
        log_file = self.logs / f'{datetime.now().strftime("%Y-%m-%d")}.json'
        
        import json
        logs = []
        if log_file.exists():
            try:
                logs = json.loads(log_file.read_text(encoding='utf-8'))
            except json.JSONDecodeError:
                logs = []
        
        logs.append(log_entry)
        log_file.write_text(json.dumps(logs, indent=2), encoding='utf-8')
    
    def get_status_summary(self) -> dict:
        """Get summary of approval workflow status."""
        return {
            'pending': len(self.get_pending_approvals()),
            'approved': len(self.get_approved_actions()),
            'rejected': len(self.get_rejected_actions())
        }


def main():
    """Main entry point for approval workflow."""
    if len(sys.argv) < 2:
        print('Usage: python approval_workflow.py <vault_path>')
        print('')
        print('Commands:')
        print('  status              - Show approval workflow status')
        print('  list pending        - List pending approvals')
        print('  list approved       - List approved actions')
        print('  list rejected       - List rejected actions')
        sys.exit(1)
    
    vault_path = sys.argv[1]
    
    if not Path(vault_path).exists():
        print(f'Error: Vault path does not exist: {vault_path}')
        sys.exit(1)
    
    workflow = ApprovalWorkflow(vault_path)
    
    if len(sys.argv) < 3:
        # Show status
        status = workflow.get_status_summary()
        print('=' * 50)
        print('Approval Workflow Status')
        print('=' * 50)
        print(f'Pending:   {status["pending"]}')
        print(f'Approved:  {status["approved"]}')
        print(f'Rejected:  {status["rejected"]}')
        print('=' * 50)
    else:
        command = sys.argv[2]
        
        if command == 'status':
            status = workflow.get_status_summary()
            print(f'Pending: {status["pending"]}')
            print(f'Approved: {status["approved"]}')
            print(f'Rejected: {status["rejected"]}')
        
        elif command == 'list':
            if len(sys.argv) < 4:
                print('Usage: python approval_workflow.py <vault_path> list <pending|approved|rejected>')
                sys.exit(1)
            
            list_type = sys.argv[3]
            
            if list_type == 'pending':
                files = workflow.get_pending_approvals()
                print(f'Pending Approvals ({len(files)}):')
                for f in files:
                    print(f'  - {f.name}')
            
            elif list_type == 'approved':
                files = workflow.get_approved_actions()
                print(f'Approved Actions ({len(files)}):')
                for f in files:
                    print(f'  - {f.name}')
            
            elif list_type == 'rejected':
                files = workflow.get_rejected_actions()
                print(f'Rejected Actions ({len(files)}):')
                for f in files:
                    print(f'  - {f.name}')


if __name__ == '__main__':
    main()
